// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDET9rbMumIyCx8PqfOVfZN_4xb8EHbd_s',
    appId: '1:777619474279:web:dd20d56ec27d329442d1c2',
    messagingSenderId: '777619474279',
    projectId: 'mentasia-7976b',
    authDomain: 'mentasia-7976b.firebaseapp.com',
    storageBucket: 'mentasia-7976b.appspot.com',
    measurementId: 'G-K1X3HGQCWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpgnfOFZjjffXo5VJzy5FYRE4M32vCVU',
    appId: '1:777619474279:android:11791b44fe96e75542d1c2',
    messagingSenderId: '777619474279',
    projectId: 'mentasia-7976b',
    storageBucket: 'mentasia-7976b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuJMSlZwmqmgGkn_9cbp3tS13TrQ-wDvE',
    appId: '1:777619474279:ios:4684fe528599680342d1c2',
    messagingSenderId: '777619474279',
    projectId: 'mentasia-7976b',
    storageBucket: 'mentasia-7976b.appspot.com',
    iosClientId: '777619474279-q0m53pu42fcjho9nsl4p5388379jlpia.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentasia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuJMSlZwmqmgGkn_9cbp3tS13TrQ-wDvE',
    appId: '1:777619474279:ios:4684fe528599680342d1c2',
    messagingSenderId: '777619474279',
    projectId: 'mentasia-7976b',
    storageBucket: 'mentasia-7976b.appspot.com',
    iosClientId: '777619474279-q0m53pu42fcjho9nsl4p5388379jlpia.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentasia',
  );
}
